#!/usr/bin/env bash
# Emit a Compose override that runs one emulator per person named on the command
# line, each installing that person's APK:
#
#   ./docker/gen-scenario.sh bob,grandma > docker-compose.scenario.yml
#
# The first person reuses the `emulator` service from docker-compose.yml (so the
# single-emulator path and `make dev`, which attaches to that service's network
# namespace, keep working untouched); each additional person gets a numbered
# sibling service. They are generated rather than hand-written because how many
# there are is up to whoever runs the scenario.
#
# All instances share the one AVD baked into the image and boot it `-read-only`
# (see docker/emulator-entrypoint.sh), which is what lets them run side by side.
set -euo pipefail

usage() {
  echo "usage: $0 <person>[,<person>...]   e.g. $0 bob,grandma" >&2
  exit 2
}

[ $# -eq 1 ] || usage
IFS=, read -ra people <<< "$1"
[ "${#people[@]}" -ge 1 ] || usage

emulator_body() {  # emulator_body <person>
  cat <<YAML
    environment:
      SERVER_HOST: server
      SERVER_PORT: "8080"
      APK_PATH: /apk/app-debug-$1.apk
      APP_ID: com.tdashroy.goober
      CLIENT_PROFILE: $1
      DISPLAY: \${DISPLAY:-:0}
      EMULATOR_GPU: \${EMULATOR_GPU:-host}
YAML
}

cat <<YAML
# Generated by docker/gen-scenario.sh — do not edit; \`make scenario\` rewrites it.
# One emulator per person, each running the app signed in as them.
services:
YAML

index=0
for person in "${people[@]}"; do
  person="${person// /}"
  [ -n "$person" ] || continue
  index=$((index + 1))

  if [ "$index" -eq 1 ]; then
    # Reuse the base `emulator` service, pointing it at this person's APK.
    echo "  emulator:"
    emulator_body "$person"
    continue
  fi

  # A sibling instance. Same image, same devices and display; its own container,
  # its own window, its own adb server.
  cat <<YAML
  emulator-${index}:
    image: goober-emulator:latest
    profiles: ["emulator"]
    privileged: true
    devices:
      - "/dev/kvm:/dev/kvm"
      - "/dev/dri:/dev/dri"
    volumes:
      - apk:/apk
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      server:
        condition: service_healthy
YAML
  emulator_body "$person"
done
